<?php
$config=array(
"ver"=>"1.0.0.rc6",
"dev"=>true,
"ws_dotaciones_url"=>"https://esb.gcba.gob.ar/dotacion",
"ws_dotacion_uss"=>"dotacion@buenosaires.gob.ar",
"ws_dotacion_pss"=>"ah21cAg",
"cookie_timeout"=>mktime(0,0,0,1,1,2035)
);
?>